version: 2
jobs:
 build:
  # Variable expansion in working_directory not supported at this time
  # You will need to modify the code below to reflect your github account/repo setup
  working_directory: /go/src/github.com/VickoSteish/gowebapp
  docker:
   - image: circleci/golang:latest
  steps:
   - checkout
   - setup_remote_docker

   - run:
      name: Build
      command: |
          echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin;
          docker build -t vickosteish/gowebapp .;
          docker push vickosteish/gowebapp;

   - deploy:
       name: Deploy
       command: |
         ssh -o StrictHostKeyChecking=no root@89.208.85.107 docker pull vickosteish/gowebapp:latest
         ssh root@89.208.85.107 docker stop gowebapp
         ssh root@89.208.85.107 docker rm gowebapp
         ssh root@89.208.85.107 docker run -d --name=gowebapp --restart=always -p 8080:8080 vickosteish/invoicer-chapter2:latest
