version: 2
jobs:
 build:
  machine:
   - image: circleci/golang:1.10
  steps:
   - add_ssh_keys:
      fingerprints:
         - "5d:1a:2f:ee:74:7a:90:9a:39:5f:ee:f0:6f:46:33:51"

   - run: 
      name: building
      command: |
       echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin;
       docker build -t vickosteish/gowebapp .;
       docker push vickosteish/gowebapp;
       
   - run:
      name: deploying
      command: |
       if [ "${CIRCLE_BRANCH}" == "main" ]; then
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@89.208.85.107 <<'ENDSSH'
         docker pull vickosteish/gowebapp
         docker stop gowebapp
         docker rm gowebapp
         docker run --name=gowebapp --restart=always -d -p 8080:8080 vickosteish/gowebapp
         ENDSSH
       fi
